info.onCountdownEnd(function () {
    Powerup = 0
    Duck.setImage(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . b b b b b b . . . . 
        . . . . . b b 5 5 5 5 5 b . . . 
        . . . . b b 5 d 1 f 5 5 d f . . 
        . . . . b 5 5 1 f f 5 d 4 c . . 
        . . . . b 5 5 d f b d d 4 4 . . 
        . b b b d 5 5 5 5 5 4 4 4 4 4 . 
        . d d d b b d 5 5 4 4 4 4 4 b . 
        . b d 5 5 5 b 5 5 5 5 5 5 b . . 
        . d c 5 5 5 5 d 5 5 5 5 5 5 b . 
        . b d c d 5 5 b 5 5 5 5 5 5 b . 
        . c d d c c b d 5 5 5 5 5 d b . 
        . . c b d d d d d 5 5 5 b b . . 
        . . . c c c c c c c c b b . . . 
        . . . . . . . . . . . . . . . . 
        `)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`tile1`, function (sprite, location) {
    tiles.setTileAt(location, assets.tile`transparency16`)
    info.changeScoreBy(1)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`tile2`, function (sprite, location) {
    sprite.startEffect(effects.fire, 3000)
    tiles.setTileAt(location, assets.tile`transparency16`)
    Powerup = 1
    info.startCountdown(3)
    Duck.setImage(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . 2 2 2 2 2 2 . . . . 
        . . . . . 2 2 5 5 5 5 5 b . . . 
        . . . . 2 2 5 d 1 f 5 5 d f . . 
        . . . . 2 5 5 1 f f 5 d 4 c . . 
        . . . . 2 5 5 d f b d d 4 4 . . 
        . 2 2 2 d 5 5 5 5 5 4 4 4 4 4 . 
        . d d d b b d 5 5 4 4 4 4 4 2 . 
        . 2 d 5 5 5 b 5 5 5 5 5 5 2 . . 
        . d c 5 5 5 5 d 5 5 5 5 5 5 2 . 
        . 2 d c d 5 5 b 5 5 5 5 5 5 2 . 
        . 2 d d c c b d 5 5 5 5 5 d 2 . 
        . . 2 b d d d d d 5 5 5 2 2 . . 
        . . . 2 2 2 2 2 2 2 2 2 2 . . . 
        . . . . . . . . . . . . . . . . 
        `)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    if (Powerup == 1) {
        tiles.placeOnRandomTile(otherSprite, sprites.dungeon.collectibleRedCrystal)
    } else {
        game.over(false)
    }
})
let Powerup = 0
let Duck: Sprite = null
tiles.setTilemap(tilemap`level1`)
Duck = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 5 5 5 5 5 b . . . 
    . . . . b b 5 d 1 f 5 5 d f . . 
    . . . . b 5 5 1 f f 5 d 4 c . . 
    . . . . b 5 5 d f b d d 4 4 . . 
    . b b b d 5 5 5 5 5 4 4 4 4 4 . 
    . d d d b b d 5 5 4 4 4 4 4 b . 
    . b d 5 5 5 b 5 5 5 5 5 5 b . . 
    . d c 5 5 5 5 d 5 5 5 5 5 5 b . 
    . b d c d 5 5 b 5 5 5 5 5 5 b . 
    . c d d c c b d 5 5 5 5 5 d b . 
    . . c b d d d d d 5 5 5 b b . . 
    . . . c c c c c c c c b b . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
tiles.placeOnRandomTile(Duck, sprites.dungeon.collectibleRedCrystal)
scene.cameraFollowSprite(Duck)
let No_Ghosts = 4
controller.moveSprite(Duck, 80, 80)
let Ghost = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
let G2 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
let G3 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
let G4 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
tiles.placeOnTile(Ghost, tiles.getTileLocation(1, 3))
tiles.placeOnTile(G2, tiles.getTileLocation(8, 3))
tiles.placeOnTile(G3, tiles.getTileLocation(1, 11))
tiles.placeOnTile(G4, tiles.getTileLocation(8, 11))
Ghost.follow(Duck, 30)
G2.follow(Duck, 40)
G3.follow(Duck, 50)
G4.follow(Duck, 60)
